#!/usr/bin/env python3
"""Generate src/aruco_dicts.zig from OpenCV's predefined ArUco dictionaries.

Usage:
    uv run --with opencv-python-headless scripts/gen_aruco_dicts.py > src/aruco_dicts.zig

Only the four *_1000 tables are emitted: the smaller standard dictionaries
(DICT_4X4_50 etc.) are prefixes of the corresponding *_1000 dictionary.
Bit convention: row-major, MSB first, bit 1 = white cell.
"""
import sys

try:
    import cv2
except ImportError:
    sys.exit("opencv-python-headless required. Run: uv run --with opencv-python-headless scripts/gen_aruco_dicts.py")

FAMILIES = [
    (4, cv2.aruco.DICT_4X4_1000),
    (5, cv2.aruco.DICT_5X5_1000),
    (6, cv2.aruco.DICT_6X6_1000),
    (7, cv2.aruco.DICT_7X7_1000),
]


def marker_code(d, n, marker_id):
    # sidePixels = n+2 renders exactly one pixel per cell, including the
    # 1-cell black border — the unambiguous ground truth for bit extraction.
    img = cv2.aruco.generateImageMarker(d, marker_id, n + 2)
    assert img.shape == (n + 2, n + 2)
    assert (img[0, :] < 128).all() and (img[-1, :] < 128).all(), "border must be black"
    assert (img[:, 0] < 128).all() and (img[:, -1] < 128).all(), "border must be black"
    inner = img[1:-1, 1:-1]
    code = 0
    for r in range(n):
        for c in range(n):
            code = (code << 1) | (1 if inner[r, c] > 127 else 0)
    return code


def main():
    out = []
    out.append("// Generated by scripts/gen_aruco_dicts.py — do not edit.")
    out.append("// Bit convention: row-major, MSB first; bit 1 = white cell.")
    out.append("")
    for n, enum_val in FAMILIES:
        d = cv2.aruco.getPredefinedDictionary(enum_val)
        codes = [marker_code(d, n, i) for i in range(1000)]
        assert len(set(codes)) == 1000, f"{n}x{n}: duplicate codes"
        out.append(f"pub const dict_{n}x{n}_maxcorr: u8 = {int(d.maxCorrectionBits)};")
        hex_width = (n * n + 3) // 4
        out.append(f"pub const dict_{n}x{n} = [_]u64{{")
        for i in range(0, 1000, 8):
            out.append("    " + " ".join(f"0x{c:0{hex_width}x}," for c in codes[i : i + 8]))
        out.append("};")
        out.append("")
    sys.stdout.write("\n".join(out))


main()
